# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ObjectBrowser.ui'
#
# Created: Sun Feb 24 19:23:02 2013
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ObjectBrowser(object):
    def setupUi(self, ObjectBrowser):
        ObjectBrowser.setObjectName("ObjectBrowser")
        ObjectBrowser.resize(706, 553)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pathLabel = QtGui.QLabel(self.dockWidgetContents)
        self.pathLabel.setObjectName("pathLabel")
        self.horizontalLayout.addWidget(self.pathLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.browseButton = QtGui.QPushButton(self.dockWidgetContents)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout.addWidget(self.browseButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listView = QtGui.QListView(self.dockWidgetContents)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.idLine = QtGui.QLineEdit(self.groupBox)
        self.idLine.setObjectName("idLine")
        self.horizontalLayout_4.addWidget(self.idLine)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.xLine = QtGui.QLineEdit(self.groupBox)
        self.xLine.setObjectName("xLine")
        self.horizontalLayout_3.addWidget(self.xLine)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.yLine = QtGui.QLineEdit(self.groupBox)
        self.yLine.setObjectName("yLine")
        self.horizontalLayout_3.addWidget(self.yLine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.laLine = QtGui.QLineEdit(self.groupBox)
        self.laLine.setObjectName("laLine")
        self.horizontalLayout_2.addWidget(self.laLine)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.raLine = QtGui.QLineEdit(self.groupBox)
        self.raLine.setObjectName("raLine")
        self.horizontalLayout_2.addWidget(self.raLine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.isThrowable = QtGui.QCheckBox(self.groupBox)
        self.isThrowable.setObjectName("isThrowable")
        self.verticalLayout_2.addWidget(self.isThrowable)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.objects = QtGui.QListView(self.groupBox)
        self.objects.setObjectName("objects")
        self.verticalLayout_3.addWidget(self.objects)
        self.neighbors = QtGui.QListView(self.groupBox)
        self.neighbors.setObjectName("neighbors")
        self.verticalLayout_3.addWidget(self.neighbors)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        ObjectBrowser.setWidget(self.dockWidgetContents)

        self.retranslateUi(ObjectBrowser)
        QtCore.QMetaObject.connectSlotsByName(ObjectBrowser)

    def retranslateUi(self, ObjectBrowser):
        ObjectBrowser.setWindowTitle(QtGui.QApplication.translate("ObjectBrowser", "DockWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.pathLabel.setText(QtGui.QApplication.translate("ObjectBrowser", "path", None, QtGui.QApplication.UnicodeUTF8))
        self.browseButton.setText(QtGui.QApplication.translate("ObjectBrowser", "browse", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ObjectBrowser", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ObjectBrowser", "Id: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ObjectBrowser", "X: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ObjectBrowser", "Y: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ObjectBrowser", "langle: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ObjectBrowser", "rangle: ", None, QtGui.QApplication.UnicodeUTF8))
        self.isThrowable.setText(QtGui.QApplication.translate("ObjectBrowser", "Is Throwable", None, QtGui.QApplication.UnicodeUTF8))

